export const LANDING_TEXTS = {
	NAME: 'Tasnid Mahin',
	HI_NAME: 'Hi, I am Tasnid Mahin',
	SOFTWARE_ENGINEER: 'Software Engineer',
	A_SOFTWARE_ENGINEER: 'A Software Engineer',
	A_FULL_STACK_DEVELOPER: 'A Full Stack Developer',
	FULL_STACK_DEVELOPER: 'Full Stack Developer',
	A_FRONT_END_DEVELOPER: 'A Front End Developer',
	FRONTEND_DEVELOPMENT_SKILLS: 'Frontend Development Skills',
	BACKEND_DEVELOPMENT_SKILLS: 'Backend Development Skills',
	TOOLS_OTHERS: 'Tools & Others',
	ANGULAR: 'Angular',
	TYPESCRIPT: 'Typescript',
	JAVASCRIPT: 'Javascript',
	NGXS: 'NGXS',
	SCSS: 'SCSS',
	TAILWIND: 'Tailwind',
	JEST: 'Jest',
	FIGMA: 'Figma',
	PRIMENG: 'PrimeNG',
	JAVA: 'Java',
	SPRING_BOOT: 'Spring Boot',
	MYSQL: 'MySQL',
	AWS: 'AWS',
	KAFKA: 'Kafka',
	REDIS: 'Redis',
	JUNIT: 'JUnit',
	MOCKITO: 'Mockito',
	POSTMAN: 'Postman',
	GIT: 'Git',
	SONARQUBE: 'SonarQube',
	GRAFANA: 'Grafana',
}